apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-user-svc
  name: api-user-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: api-user-svc
