apiVersion: v1
kind: Service
metadata:
  labels:
    service: rp-svc
  name: rp-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: rp-svc
  type: LoadBalancer
